### ISSUE TITLE
Segmentation Fault when running motion_wizard

### ISSUE THREAD

**Issue by SergioFernandezCordero** [jespino/camtones#1]
Hi,

First of all, thanks for this great job. I'm trying to use camtones to analyse deep sky video taken with a cam to detect meteors, and it's the simplest approach I've found to do it.

I've installed camtones in Deban Testing but when I try to run motion_wizard with an .avi video, it doesn't open, and returns "Segmentation Fault".

I've installed camtones from git repo, against manually compiled opencv 3.1, following official documentation: http://docs.opencv.org/3.0-beta/doc/tutorials/introduction/linux_install/linux_install.html
Also, installing via pip produces the same result.

Apparently, other functions, as motion_extract works?

How can I help you make this software beter?

**Comment by jespino** [comment]
motion_wizard is a gtk interface to "tune" the options for motion_extract. motion_wizard isn't really needed, but of course is really useful to start using camtones.

I will try to install it and run it and I say you something more.

**Comment by jespino** [comment]
This is a problem with the GTK library, I'm not sure why is failing, I have to investigate it more deeply.

**Comment by jespino** [comment]
It is a GTK bug related to GDKPixBuf (https://bugzilla.gnome.org/show_bug.cgi?id=732297) I have made a workaround to avoid the segmentation fault. Can you try now? To understand better how works is better to use a video with a fixed cam and with movement in one zone.

**Comment by SergioFernandezCordero** [comment]
Hi @jespino, with the workaround motion_wizard works like a charm! Thank you very much.

**Comment by jespino** [comment]
Great! About how to help to make this software better is reporting this kind of bugs, and any improvement suggestion. Of course, I accept Pull Requests too.
